CREATE TABLE `db`.`python` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `jobname` VARCHAR(255) NOT NULL,
  `com_id` INT NULL,
  `money` VARCHAR(45) NULL,
  `url` VARCHAR(255) NULL,
  `origin` VARCHAR(45) NULL,
  `natural` VARCHAR(45) NULL,
  `exp` VARCHAR(255) NULL,
  `education` VARCHAR(45) NULL,
  `time` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `url_UNIQUE` (`url` ASC),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  UNIQUE INDEX `com_id_UNIQUE` (`com_id` ASC));